### ISSUE TITLE
Getting this error in offline mode

### ISSUE THREAD

**Issue by sajualways** [Macr0phag3/ja3box#4]
ERROR: Loading module scapy.layers.tls.all
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/scapy/main.py", line 163, in _load
    mod = importlib.import_module(module)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/scapy/layers/tls/all.py", line 12, in <module>
    from scapy.layers.tls.automaton_cli import *  # noqa: F401
  File "/usr/local/lib/python3.6/site-packages/scapy/layers/tls/automaton_cli.py", line 48, in <module>
    from scapy.layers.tls.automaton import _TLSAutomaton
  File "/usr/local/lib/python3.6/site-packages/scapy/layers/tls/automaton.py", line 20, in <module>
    from scapy.layers.tls.record import TLS
  File "/usr/local/lib/python3.6/site-packages/scapy/layers/tls/record.py", line 27, in <module>
    from scapy.layers.tls.handshake import (_tls_handshake_cls, _TLSHandshake,
  File "/usr/local/lib/python3.6/site-packages/scapy/layers/tls/handshake.py", line 45, in <module>
    from scapy.layers.tls.extensions import (_ExtensionsLenField, _ExtensionsField,
  File "/usr/local/lib/python3.6/site-packages/scapy/layers/tls/extensions.py", line 20, in <module>
    from scapy.layers.tls.keyexchange import (SigAndHashAlgsLenField,
  File "/usr/local/lib/python3.6/site-packages/scapy/layers/tls/keyexchange.py", line 26, in <module>
    from scapy.layers.tls.crypto.groups import (
  File "/usr/local/lib/python3.6/site-packages/scapy/layers/tls/crypto/groups.py", line 27, in <module>
    from cryptography.hazmat.primitives.asymmetric import x448
ImportError: cannot import name 'x448'
[!] Something went wrong: name 'TLS' is not defined

**Comment by Macr0phag3** [comment]
hello, after testing, ja3box works fine in
- python: 3.6.0/...
- scapy: 2.4.5
- cryptography: 2.8/3.4.7/...

You can try to update the cryptography: `pip install cryptography -U`
@sajualways

**Comment by sajualways** [comment]
I am getting this error now.

pip3.6 install cryptography -U
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3.6 install --user` instead.
Collecting cryptography
  Using cached https://files.pythonhosted.org/packages/9b/77/461087a514d2e8ece1c975d8216bc03f7048e6090c5166bc34115afdaa53/cryptography-3.4.7.tar.gz
    Complete output from command python setup.py egg_info:
    
            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:
    
            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0v_g5l0l/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0v_g5l0l/cryptography/

**Comment by sajualways** [comment]
I am getting this error now
pip3.6 install cryptography -U
WARNING: Running pip install with root privileges is generally not a good
idea. Try `pip3.6 install --user` instead.
Collecting cryptography
  Using cached
https://files.pythonhosted.org/packages/9b/77/461087a514d2e8ece1c975d8216bc03f7048e6090c5166bc34115afdaa53/cryptography-3.4.7.tar.gz
    Complete output from command python setup.py egg_info:

            =============================DEBUG
ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:

            Upgrade to the latest pip and try again. This will fix errors
for most
            users. See:
https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG
ASSISTANCE==========================

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-0v_g5l0l/cryptography/setup.py", line 14, in
<module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in
/tmp/pip-build-0v_g5l0l/cryptography/

**Comment by Macr0phag3** [comment]
upgrading pip solved it.
`pip3.6 install -U pip`

:)

@sajualways

**Comment by sajualways** [comment]
Thanks a lot.....It is working now.
